- task: CmdLine@1
  displayName: Patch AssemblyFileVersion
  inputs:
    filename: perl
    arguments: [% base_dir %]/AssemblyInfoPatchVersion.pl "\$(Build.BuildId)"
    workingDirectory: "\$(Build.SourcesDirectory)"

